# Generated by Django 2.0.2 on 2018-04-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180414_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
    ]
